<a href="https://colab.research.google.com/github/GabrielWateyma/Couses/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

# Creating constant tensors
tensor_a = tf.constant([[1, 2],
                        [3, 4]])
tensor_b = tf.constant([[5, 6],
                        [7, 8]])

print("Tensor A:")
print(tensor_a)
print("\nTensor B:")
print(tensor_b)

# Performing addition
tensor_sum = tf.add(tensor_a, tensor_b)
print("\nSum of Tensor A and Tensor B:")
print(tensor_sum)

Tensor A:
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

Tensor B:
tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)

Sum of Tensor A and Tensor B:
tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


In [ ]:
import tensorflow as tf
from tensorflow import keras

# Define a simple sequential model
model = keras.Sequential([
    keras.layers.Dense(128, activation='relu', input_shape=(784,)), # Input layer with 784 features (e.g., for MNIST images)
    keras.layers.Dense(10, activation='softmax') # Output layer with 10 classes (e.g., for MNIST digits)
])

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Print a summary of the model architecture
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 128)            │       100,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 101,770 (397.54 KB)

 Trainable params: 101,770 (397.54 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
import tensorflow as tf
from tensorflow import keras

# Load the MNIST dataset
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Preprocess the data: Normalize pixel values to be between 0 and 1
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Flatten the images from 28x28 to 784 features
x_train_flattened = x_train.reshape(-1, 784)
x_test_flattened = x_test.reshape(-1, 784)

# Define the same sequential model as before
model = keras.Sequential([
    keras.layers.Dense(128, activation='relu', input_shape=(784,)),
    keras.layers.Dense(10, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
epochs = 5 # You can increase this number for potentially better accuracy
batch_size = 32 # Adjust batch size as needed
model.fit(x_train_flattened, y_train, epochs=epochs, batch_size=batch_size, validation_split=0.2) # Use a portion of the training data for validation

# Evaluate the model on the test set
loss, accuracy = model.evaluate(x_test_flattened, y_test, verbose=0)
print(f"\nTest Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Epoch 1/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8652 - loss: 0.4703 - val_accuracy: 0.9550 - val_loss: 0.1633
Epoch 2/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9591 - loss: 0.1433 - val_accuracy: 0.9666 - val_loss: 0.1180
Epoch 3/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9729 - loss: 0.0904 - val_accuracy: 0.9690 - val_loss: 0.1083
Epoch 4/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9787 - loss: 0.0679 - val_accuracy: 0.9693 - val_loss: 0.0992
Epoch 5/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9857 - loss: 0.0512 - val_accuracy: 0.9736 - val_loss: 0.0963

Test Loss: 0.0874
Test Accuracy: 0.9729


In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

# Load the MNIST dataset (again, as the input shape is different for CNNs)
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Preprocess the data: Normalize pixel values to be between 0 and 1
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Reshape the input data for CNNs (add a channel dimension)
# MNIST images are grayscale, so the channel dimension is 1
x_train = x_train.reshape(x_train.shape[0], 28, 28, 1)
x_test = x_test.reshape(x_test.shape[0], 28, 28, 1)

# Convert labels to one-hot encoding
y_train = keras.utils.to_categorical(y_train, num_classes=10)
y_test = keras.utils.to_categorical(y_test, num_classes=10)

# Define a CNN model
model = keras.Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(10, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Print a summary of the model architecture
model.summary()

# Train the model
epochs = 5
batch_size = 64 # Increased batch size is often used with CNNs
model.fit(x_train, y_train, epochs=epochs, batch_size=batch_size, validation_split=0.2)

# Evaluate the model on the test set
loss, accuracy = model.evaluate(x_test, y_test, verbose=0)
print(f"\nTest Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 26, 26, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 13, 13, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 11, 11, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 5, 5, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 1600)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 10)             │        16,010 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 34,826 (136.04 KB)

 Trainable params: 34,826 (136.04 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/5
750/750 ━━━━━━━━━━━━━━━━━━━━ 37s 47ms/step - accuracy: 0.8506 - loss: 0.5333 - val_accuracy: 0.9755 - val_loss: 0.0845
Epoch 2/5
750/750 ━━━━━━━━━━━━━━━━━━━━ 41s 47ms/step - accuracy: 0.9781 - loss: 0.0760 - val_accuracy: 0.9818 - val_loss: 0.0632
Epoch 3/5
750/750 ━━━━━━━━━━━━━━━━━━━━ 40s 46ms/step - accuracy: 0.9837 - loss: 0.0520 - val_accuracy: 0.9851 - val_loss: 0.0503
Epoch 4/5
750/750 ━━━━━━━━━━━━━━━━━━━━ 44s 51ms/step - accuracy: 0.9870 - loss: 0.0409 - val_accuracy: 0.9858 - val_loss: 0.0465
Epoch 5/5
750/750 ━━━━━━━━━━━━━━━━━━━━ 40s 50ms/step - accuracy: 0.9903 - loss: 0.0325 - val_accuracy: 0.9862 - val_loss: 0.0456

Test Loss: 0.0381
Test Accuracy: 0.9877


In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Load the MNIST dataset
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Preprocess the data: Normalize pixel values to be between 0 and 1
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Reshape the input data for CNNs (add a channel dimension)
x_train = x_train.reshape(x_train.shape[0], 28, 28, 1)
x_test = x_test.reshape(x_test.shape[0], 28, 28, 1)

# Convert labels to one-hot encoding
y_train = keras.utils.to_categorical(y_train, num_classes=10)
y_test = keras.utils.to_categorical(y_test, num_classes=10)

# Define the same CNN model as before
model = keras.Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(10, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Create an ImageDataGenerator for data augmentation
datagen = ImageDataGenerator(
    rotation_range=10,  # Rotate images by up to 10 degrees
    width_shift_range=0.1,  # Shift images horizontally by up to 10% of the width
    height_shift_range=0.1,  # Shift images vertically by up to 10% of the height
    zoom_range=0.1,  # Zoom in on images by up to 10%
    horizontal_flip=False)  # Don't flip images horizontally (digits usually don't need this)

# Train the model using the ImageDataGenerator
epochs = 10 # Increased epochs as augmentation often benefits from more training
batch_size = 64
model.fit(datagen.flow(x_train, y_train, batch_size=batch_size),
          epochs=epochs,
          validation_data=(x_test, y_test)) # Use test set for validation here

# No separate evaluation step needed as validation is done during training

Epoch 1/10


/usr/local/lib/python3.11/dist-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


938/938 ━━━━━━━━━━━━━━━━━━━━ 63s 65ms/step - accuracy: 0.7646 - loss: 0.7416 - val_accuracy: 0.9819 - val_loss: 0.0642
Epoch 2/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 61s 65ms/step - accuracy: 0.9476 - loss: 0.1736 - val_accuracy: 0.9858 - val_loss: 0.0460
Epoch 3/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 59s 62ms/step - accuracy: 0.9632 - loss: 0.1193 - val_accuracy: 0.9874 - val_loss: 0.0409
Epoch 4/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 60s 64ms/step - accuracy: 0.9697 - loss: 0.0995 - val_accuracy: 0.9880 - val_loss: 0.0391
Epoch 5/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 60s 63ms/step - accuracy: 0.9736 - loss: 0.0868 - val_accuracy: 0.9889 - val_loss: 0.0356
Epoch 6/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 60s 63ms/step - accuracy: 0.9759 - loss: 0.0780 - val_accuracy: 0.9886 - val_loss: 0.0371
Epoch 7/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 59s 62ms/step - accuracy: 0.9787 - loss: 0.0702 - val_accuracy: 0.9916 - val_loss: 0.0299
Epoch 8/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 61s 65ms/step - accuracy: 0.9812 - loss: 0.0631 - val_accurac